CC = g++
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)
INCLUDE = -I.

all: hanoi.cpp area.cpp
	$(CC) $(LFLAGS) $(INCLUDE) hanoi.cpp -o hanoi
	$(CC) $(LFLAGS) $(INCLUDE) area.cpp -o area
g++ -Wall -g -I. hanoi.cpp -o hanoi
g++ -Wall -g -I. factorial.cpp -o fact
